POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzAzMjUxMjY4LCJpc0FkbWluIjp0cnVlLCJ1c2VySWQiOjF9.TebKdIBnuT4cpX3YsabcoznH8TNFjmq0GkZ-Fv4m-6U

{
	"name": "New test event3",
	"description": "A new test event",
	"location": "A new test location",
	"dateTime": "2025-01-01T15:30:00.000Z"
}