GET http://localhost:8080/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzAzMjU5ODM0LCJpc0FkbWluIjp0cnVlLCJ1c2VySWQiOjF9.hW2KFNy-ikpb49PjKS5z-Jy85A943cqw4kMGOOgI84Q